server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: user_service_app
    password: postgres@123

  security:
    user:
      name: parth
      password: parth@123


jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  application:
    name: user-service